- name: vars preferance
  hosts: local
  connection: local
  vars: 
   NAME: from play level
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: what is your NAME?
    private: false
  tasks:
  - name: testing variables preferance
    vars:
    NAME: from task level 
    ansible.builtin.debug:
      msg: "NAME: {{ NAME }}"